apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8080
  leaderElection: true
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          {{#each azure.groups as |group|}}
             - id: {{group.objectId}}
            {{/each}}
      singlePageApplication: true
      replyURLs:
        {{#each azure.replyURLs as |url|}}
           - {{url}}
          {{/each}}
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: endringsmelding-pleiepenger
        - application: dine-pleiepenger
        - application: k9-brukerdialog-api
        - application: k9-sak-innsyn-api # Kaller hit for legacy søknader.
    outbound:
      external:
        {{#each externalHosts as |host|}}
        - host: {{host}}
        {{/each}}
      rules:
        - application: k9-selvbetjening-oppslag
        - application: k9-sak-innsyn-api
  liveness:
    path: /health/liveness
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /health/readiness
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 3072Mi
    requests:
      cpu: 80m
      memory: 1536Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: {{observabilityEnabled}}
      runtime: java
  env:
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
  gcp:
    sqlInstances:
      - type: {{ database.type }}
        tier: {{ database.tier }}
        diskSize: {{ database.diskSize }}
        diskAutoresize: {{ database.diskAutoresize }}
        highAvailability: {{ database.highAvailability }}
        databases:
          - name: {{ database.name }}
  kafka:
    pool: {{kafkaPool}}
