name: Vulnerabilities scanning of dependencies
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 3 * * *'

env:
  IMAGE: navikt/sif-innsyn-api:${{ github.sha }}
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        with:
          command: monitor
          args: --org=dusseldorf --configuration-matching="^runtimeClasspath$|^compileClasspath$" --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git
